version: "3.8"
services:
  frontend: 
    build: ./frontend
    depends_on:
      - api
    ports: 
      - "3000:3000"
    networks:
      - shareapplication
  api:
    build: ./backend/api
    depends_on: 
      - db
    ports:
      - "3002:3002"
    networks:
      - shareapplication
  calculation-engine: 
    build: ./backend/calculation-engine
    depends_on: 
      - db
    networks:
      - shareapplication
  db:
    build: ./backend
    ports: 
      - "5432:5432"
    networks: 
      - shareapplication 
networks:
  shareapplication: 
      driver: bridge